{% set name = "loop-rate-limiters" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loop-rate-limiters-{{ version }}.tar.gz
  sha256: ff28c1dc19070d48a740d58cf3023dd49ade090cb5e3edce37e03601f4f28675

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - flit >=2,<4
  run:
    - python >=3.8

test:
  imports:
    - loop_rate_limiters
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://pypi.org/project/loop-rate-limiters/
  summary: Loop rate limiters.
  dev_url: https://github.com/stephane-caron/loop-rate-limiters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
